apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "atm.name" . }}
  labels:
    {{- include "atm.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "atm.selectorLabels" . | nindent 6 }}
